// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/ARCoPilotScreen.tsx": () => import("../components/mockups/ARCoPilotScreen.tsx"),
  "./components/mockups/GoBabyGoBuddyLinkCanvas.tsx": () => import("../components/mockups/GoBabyGoBuddyLinkCanvas.tsx"),
  "./components/mockups/HomeScreen.tsx": () => import("../components/mockups/HomeScreen.tsx"),
  "./components/mockups/MissionsScreen.tsx": () => import("../components/mockups/MissionsScreen.tsx"),
  "./components/mockups/ParentModeScreen.tsx": () => import("../components/mockups/ParentModeScreen.tsx"),
  "./components/mockups/SessionSummaryScreen.tsx": () => import("../components/mockups/SessionSummaryScreen.tsx")
};
